[project]
name = "rpi-eink-dashboard"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gpiozero>=2.0.1",
    "pillow>=11.2.1",
    "requests>=2.32.3",
    "spidev>=3.6",
]
